# Generated by Django 5.1 on 2024-08-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="instruction_text",
            field=models.TextField(default=""),
        ),
    ]
