# Generated by Django 5.1 on 2024-08-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0002_poll_instruction_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Histogram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_bins", models.IntegerField(default=8)),
            ],
        ),
    ]
