# Generated by Django 5.1 on 2024-08-21 18:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0003_histogram"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Histogram",
        ),
    ]
